package com.ali.lz.effect.hadooputils;

public class EffectJobStatusCounter {
    public enum FinderJobProcessStatus {
        HOLOTREE_OUTPUT_ERROR, HOLOTREE_OUTPUT_RIGHT, REDUCE_OUTPUT_RIGHT, HOLOTREE_OUTPUT_NODE_COUNT, PB_DESERIALIZE_ERROR
    }

    public enum TreeBuilderStatus {
        LOG_FORMAT_ERROR, IS_EFFECT_PAGE, REFER_IS_EFFECT_PAGE, IS_EFFECT_ITEM_PIT, IS_EFFECT_SHOP_PIT, IS_EFFECT_LIST_PIT, IS_EFFECT_LIST_PIT_ITEMS
    }

    public enum WirelessOwnershipStatus {
        WIRELESS_OWNERSHIP_BROWSE_LOG, WIRELESS_OWNERSHIP_GMV_LOG, WIRELESS_OWNERSHIP_ACTIVITY_PAGE, WIRELESS_OWNERSHIP_ITEM_PIT_PAGE, WIRELESS_OWNERSHIP_LISTITEM_PIT_PAGE, WIRELESS_OWNERSHIP_SHOP_PIT_PAGE, WIRELESS_OWNERSHIP_IPV_PAGE, WIRELESS_OWNERSHIP_OWNER_IPV_ITEM, WIRELESS_OWNERSHIP_OWNER_GMV_ITEM, WIRELESS_OWNERSHIP_OWNER_IPV_SHOP, WIRELESS_OWNERSHIP_OWNER_GMV_SHOP, WIRELESS_OWNERSHIP_OWNER_OTHER, WIRELESS_OWNERSHIP_OWNER_NOPLANMAP
    }

    public enum PidOwnershipStatus {
        PID_OWNERSHIP_BROWSE_LOG, PID_OWNERSHIP_GMV_LOG, PID_OWNERSHIP_ACTIVITY_PAGE, PID_OWNERSHIP_ACTIVITY_CLICK_PAGE, PID_OWNERSHIP_ITEM_PIT_PAGE, PID_OWNERSHIP_LISTITEM_PIT_PAGE, PID_OWNERSHIP_LIST_PIT_PAGE, PID_OWNERSHIP_SHOP_PIT_PAGE, PID_OWNERSHIP_IPV_PAGE, PID_OWNERSHIP_OWNER_IPV_ITEM, PID_OWNERSHIP_OWNER_GMV_ITEM, PID_OWNERSHIP_OWNER_IPV_SHOP, PID_OWNERSHIP_OWNER_GMV_SHOP, PID_OWNERSHIP_OWNER_OTHER, PID_OWNERSHIP_OWNER_NOPLANMAP
    }

    public enum EffectOwnershipStatus {
        HOLOTREE_LOG_FORMAT_ERROR, GMV_LOG_FORMAT_ERROR, COLLECT_LOG_FORMAT_ERROR, CART_LOG_FORMAT_ERROR, PB_DESERIALIZE_ERROR,
    }

    public enum EffectHjljOwnershipStatus {
        INHERIT_HJLJ_LOGKEYS, INPUT_HJLJ_LOGS
    }

}
