-- ##########################################################################
-- # Owner:luqian
-- # Email:luqian@taobao.com
-- # Date:2012/09/17
-- # ------------------------------------------------------------------------
-- # Description:计算etao效果页数据
-- # Input:lz_fact_ep_etao_visit_effect, lz_fact_ep_etao_trade_ownership
-- # Onput:lz_fact_ep_etao_ownership
-- # ------------------------------------------------------------------------
-- # ChangeLog:
-- ##########################################################################

insert overwrite table lz_fact_ep_etao_ownership partition (dt='${date}')
select
    lp_src,
    lp_domain_name,
    is_lp,
    refer_is_lp,
    is_etao,
    adid,
    tb_market_id,
    refer_site,
    site_id,
    ad_id,
    apply,
    t_id,
    linkname,
    pub_id,
    pid_site_id,
    adzone_id,
    keyword,
    src_domain_name_level1,
    src_domain_name_level2,
    cookie,
    sum(pv),
    user_id,
    sum(direct_item_gmv_trade_num        ) as  direct_item_gmv_trade_num         ,
    sum(direct_item_gmv_amt              ) as  direct_item_gmv_amt               ,
    sum(direct_item_alipay_trade_num     ) as  direct_item_alipay_trade_num      ,
    sum(direct_item_alipay_amt           ) as  direct_item_alipay_amt            ,
    sum(direct_itemshop_gmv_trade_num    ) as  direct_itemshop_gmv_trade_num    ,
    sum(direct_itemshop_gmv_amt          ) as  direct_itemshop_gmv_amt          ,
    sum(direct_itemshop_alipay_trade_num ) as  direct_itemshop_alipay_trade_num ,
    sum(direct_itemshop_alipay_amt       ) as  direct_itemshop_alipay_amt       ,
    sum(outside_gmv_trade_num            ) as  outside_gmv_trade_num        ,
    sum(outside_gmv_amt                  ) as  outside_gmv_amt              ,
    sum(outside_alipay_trade_num         ) as  outside_alipay_trade_num     ,
    sum(outside_alipay_amt               ) as  outside_alipay_amt           ,
    sum(cps_new_trade_num                ) as  cps_new_trade_num            ,
    sum(cps_new_amt                      ) as  cps_new_amt                  ,
    sum(cps_old_trade_num                ) as  cps_old_trade_num            ,
    sum(cps_old_amt                      ) as  cps_old_amt                  
from
(select 
    lp_src,
    lp_domain_name,
    is_lp,
    refer_is_lp,
    is_etao,
    adid,
    tb_market_id,
    refer_site,
    site_id,
    ad_id,
    apply,
    t_id,
    linkname,
    pub_id,
    pid_site_id,
    adzone_id,
    keyword,
    src_domain_name_level1,
    src_domain_name_level2,
    cookie,
    pv,
    user_id,
    0.0 as direct_item_gmv_trade_num,
    0.0 as direct_item_gmv_amt,
    0.0 as direct_item_alipay_trade_num,
    0.0 as direct_item_alipay_amt,            
    0.0 as direct_itemshop_gmv_trade_num, 
    0.0 as direct_itemshop_gmv_amt,          
    0.0 as direct_itemshop_alipay_trade_num, 
    0.0 as direct_itemshop_alipay_amt, 
    0.0 as outside_gmv_trade_num,        
    0.0 as outside_gmv_amt,              
    0.0 as outside_alipay_trade_num,  
    0.0 as outside_alipay_amt,           
    0.0 as cps_new_trade_num,            
    0.0 as cps_new_amt,                  
    0.0 as cps_old_trade_num,            
    0.0 as cps_old_amt                  
from lz_fact_ep_etao_visit_effect where dt='${date}'

union all

select
    lp_src,
    lp_domain_name,
    cast(0 as bigint) as is_lp,
    refer_is_lp,
    cast(0 as bigint) as is_etao,
    adid,
    tb_market_id,
    refer_site,
    site_id,
    ad_id,
    apply,
    t_id,
    linkname,
    pub_id,
    pid_site_id,
    adzone_id,
    keyword,
    src_domain_name_level1,
    src_domain_name_level2,
    cookie,
    0.0 as pv,
    user_id,
    direct_item_gmv_trade_num,
    direct_item_gmv_amt,
    direct_item_alipay_trade_num,
    direct_item_alipay_amt,            
    direct_itemshop_gmv_trade_num, 
    direct_itemshop_gmv_amt,          
    direct_itemshop_alipay_trade_num, 
    direct_itemshop_alipay_amt, 
    outside_gmv_trade_num,        
    outside_gmv_amt,              
    outside_alipay_trade_num,  
    outside_alipay_amt,           
    cps_new_trade_num,            
    cps_new_amt,                  
    cps_old_trade_num,            
    cps_old_amt                  
from lz_fact_ep_etao_trade_ownership where dt='${date}') a
group by 
    lp_src,
    lp_domain_name,
    is_lp,
    refer_is_lp,
    is_etao,
    adid,
    tb_market_id,
    refer_site,
    site_id,
    ad_id,
    apply,
    t_id,
    linkname,
    pub_id,
    pid_site_id,
    adzone_id,
    keyword,
    src_domain_name_level1,
    src_domain_name_level2,
    cookie,
    user_id
;
