// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/AplusAccessTreeNode.proto

package com.etao.data.ep.accesstree.proto;

public final class AplusAccessTreeNodeProto {
  private AplusAccessTreeNodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AplusAccessTreeNodeValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string version = 1;
    boolean hasVersion();
    String getVersion();
    
    // optional string acookie = 2;
    boolean hasAcookie();
    String getAcookie();
    
    // optional string session_cookie = 3;
    boolean hasSessionCookie();
    String getSessionCookie();
    
    // optional string tree_id = 4;
    boolean hasTreeId();
    String getTreeId();
    
    // optional string node_id = 5;
    boolean hasNodeId();
    String getNodeId();
    
    // optional string parent_id = 6;
    boolean hasParentId();
    String getParentId();
    
    // optional string parent_list = 7;
    boolean hasParentList();
    String getParentList();
    
    // optional string ip = 8;
    boolean hasIp();
    String getIp();
    
    // optional string user_agent = 9;
    boolean hasUserAgent();
    String getUserAgent();
    
    // optional string url = 10;
    boolean hasUrl();
    String getUrl();
    
    // optional string url_info = 11;
    boolean hasUrlInfo();
    String getUrlInfo();
    
    // optional string lzsession = 12;
    boolean hasLzsession();
    String getLzsession();
    
    // optional string user_id = 13;
    boolean hasUserId();
    String getUserId();
    
    // optional string nick = 14;
    boolean hasNick();
    String getNick();
    
    // optional string proxy = 15;
    boolean hasProxy();
    String getProxy();
    
    // optional string pvtime = 16;
    boolean hasPvtime();
    String getPvtime();
    
    // optional string revised_refer = 17;
    boolean hasRevisedRefer();
    String getRevisedRefer();
    
    // optional int64 ts = 18;
    boolean hasTs();
    long getTs();
    
    // optional string refer = 19;
    boolean hasRefer();
    String getRefer();
  }
  public static final class AplusAccessTreeNodeValue extends
      com.google.protobuf.GeneratedMessage
      implements AplusAccessTreeNodeValueOrBuilder {
    // Use AplusAccessTreeNodeValue.newBuilder() to construct.
    private AplusAccessTreeNodeValue(Builder builder) {
      super(builder);
    }
    private AplusAccessTreeNodeValue(boolean noInit) {}
    
    private static final AplusAccessTreeNodeValue defaultInstance;
    public static AplusAccessTreeNodeValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public AplusAccessTreeNodeValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.Object version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          version_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string acookie = 2;
    public static final int ACOOKIE_FIELD_NUMBER = 2;
    private java.lang.Object acookie_;
    public boolean hasAcookie() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAcookie() {
      java.lang.Object ref = acookie_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          acookie_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAcookieBytes() {
      java.lang.Object ref = acookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        acookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string session_cookie = 3;
    public static final int SESSION_COOKIE_FIELD_NUMBER = 3;
    private java.lang.Object sessionCookie_;
    public boolean hasSessionCookie() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSessionCookie() {
      java.lang.Object ref = sessionCookie_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionCookie_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionCookieBytes() {
      java.lang.Object ref = sessionCookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionCookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string tree_id = 4;
    public static final int TREE_ID_FIELD_NUMBER = 4;
    private java.lang.Object treeId_;
    public boolean hasTreeId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTreeId() {
      java.lang.Object ref = treeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          treeId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTreeIdBytes() {
      java.lang.Object ref = treeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        treeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string node_id = 5;
    public static final int NODE_ID_FIELD_NUMBER = 5;
    private java.lang.Object nodeId_;
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nodeId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string parent_id = 6;
    public static final int PARENT_ID_FIELD_NUMBER = 6;
    private java.lang.Object parentId_;
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parentId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string parent_list = 7;
    public static final int PARENT_LIST_FIELD_NUMBER = 7;
    private java.lang.Object parentList_;
    public boolean hasParentList() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getParentList() {
      java.lang.Object ref = parentList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parentList_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParentListBytes() {
      java.lang.Object ref = parentList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parentList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string ip = 8;
    public static final int IP_FIELD_NUMBER = 8;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string user_agent = 9;
    public static final int USER_AGENT_FIELD_NUMBER = 9;
    private java.lang.Object userAgent_;
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userAgent_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 10;
    public static final int URL_FIELD_NUMBER = 10;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url_info = 11;
    public static final int URL_INFO_FIELD_NUMBER = 11;
    private java.lang.Object urlInfo_;
    public boolean hasUrlInfo() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getUrlInfo() {
      java.lang.Object ref = urlInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          urlInfo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlInfoBytes() {
      java.lang.Object ref = urlInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        urlInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string lzsession = 12;
    public static final int LZSESSION_FIELD_NUMBER = 12;
    private java.lang.Object lzsession_;
    public boolean hasLzsession() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getLzsession() {
      java.lang.Object ref = lzsession_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          lzsession_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLzsessionBytes() {
      java.lang.Object ref = lzsession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        lzsession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string user_id = 13;
    public static final int USER_ID_FIELD_NUMBER = 13;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nick = 14;
    public static final int NICK_FIELD_NUMBER = 14;
    private java.lang.Object nick_;
    public boolean hasNick() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nick_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string proxy = 15;
    public static final int PROXY_FIELD_NUMBER = 15;
    private java.lang.Object proxy_;
    public boolean hasProxy() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getProxy() {
      java.lang.Object ref = proxy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          proxy_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProxyBytes() {
      java.lang.Object ref = proxy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        proxy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pvtime = 16;
    public static final int PVTIME_FIELD_NUMBER = 16;
    private java.lang.Object pvtime_;
    public boolean hasPvtime() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public String getPvtime() {
      java.lang.Object ref = pvtime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pvtime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPvtimeBytes() {
      java.lang.Object ref = pvtime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pvtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string revised_refer = 17;
    public static final int REVISED_REFER_FIELD_NUMBER = 17;
    private java.lang.Object revisedRefer_;
    public boolean hasRevisedRefer() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public String getRevisedRefer() {
      java.lang.Object ref = revisedRefer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          revisedRefer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRevisedReferBytes() {
      java.lang.Object ref = revisedRefer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        revisedRefer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 ts = 18;
    public static final int TS_FIELD_NUMBER = 18;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public long getTs() {
      return ts_;
    }
    
    // optional string refer = 19;
    public static final int REFER_FIELD_NUMBER = 19;
    private java.lang.Object refer_;
    public boolean hasRefer() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public String getRefer() {
      java.lang.Object ref = refer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          refer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReferBytes() {
      java.lang.Object ref = refer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        refer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      version_ = "";
      acookie_ = "";
      sessionCookie_ = "";
      treeId_ = "";
      nodeId_ = "";
      parentId_ = "";
      parentList_ = "";
      ip_ = "";
      userAgent_ = "";
      url_ = "";
      urlInfo_ = "";
      lzsession_ = "";
      userId_ = "";
      nick_ = "";
      proxy_ = "";
      pvtime_ = "";
      revisedRefer_ = "";
      ts_ = 0L;
      refer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAcookieBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionCookieBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTreeIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getParentIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getParentListBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getIpBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getUrlInfoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getLzsessionBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getUserIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getNickBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getProxyBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getPvtimeBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getRevisedReferBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt64(18, ts_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBytes(19, getReferBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAcookieBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionCookieBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTreeIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getParentIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getParentListBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getIpBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getUrlInfoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getLzsessionBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getUserIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getNickBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getProxyBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getPvtimeBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getRevisedReferBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, ts_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getReferBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_fieldAccessorTable;
      }
      
      // Construct using com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        acookie_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionCookie_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        treeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        parentList_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        urlInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        lzsession_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        nick_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        proxy_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        pvtime_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        revisedRefer_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00020000);
        refer_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.getDescriptor();
      }
      
      public com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue getDefaultInstanceForType() {
        return com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.getDefaultInstance();
      }
      
      public com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue build() {
        com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue buildPartial() {
        com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue result = new com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.acookie_ = acookie_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionCookie_ = sessionCookie_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.treeId_ = treeId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.parentId_ = parentId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.parentList_ = parentList_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.urlInfo_ = urlInfo_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.lzsession_ = lzsession_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.nick_ = nick_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.proxy_ = proxy_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.pvtime_ = pvtime_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.revisedRefer_ = revisedRefer_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.refer_ = refer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue) {
          return mergeFrom((com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue other) {
        if (other == com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasAcookie()) {
          setAcookie(other.getAcookie());
        }
        if (other.hasSessionCookie()) {
          setSessionCookie(other.getSessionCookie());
        }
        if (other.hasTreeId()) {
          setTreeId(other.getTreeId());
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (other.hasParentList()) {
          setParentList(other.getParentList());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasUserAgent()) {
          setUserAgent(other.getUserAgent());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasUrlInfo()) {
          setUrlInfo(other.getUrlInfo());
        }
        if (other.hasLzsession()) {
          setLzsession(other.getLzsession());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasNick()) {
          setNick(other.getNick());
        }
        if (other.hasProxy()) {
          setProxy(other.getProxy());
        }
        if (other.hasPvtime()) {
          setPvtime(other.getPvtime());
        }
        if (other.hasRevisedRefer()) {
          setRevisedRefer(other.getRevisedRefer());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasRefer()) {
          setRefer(other.getRefer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              version_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              acookie_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionCookie_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              treeId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              nodeId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              parentId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              parentList_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              ip_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              userAgent_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              url_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              urlInfo_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              lzsession_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              userId_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              nick_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              proxy_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              pvtime_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              revisedRefer_ = input.readBytes();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              ts_ = input.readInt64();
              break;
            }
            case 154: {
              bitField0_ |= 0x00040000;
              refer_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string version = 1;
      private java.lang.Object version_ = "";
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      void setVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
      }
      
      // optional string acookie = 2;
      private java.lang.Object acookie_ = "";
      public boolean hasAcookie() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAcookie() {
        java.lang.Object ref = acookie_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          acookie_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAcookie(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        acookie_ = value;
        onChanged();
        return this;
      }
      public Builder clearAcookie() {
        bitField0_ = (bitField0_ & ~0x00000002);
        acookie_ = getDefaultInstance().getAcookie();
        onChanged();
        return this;
      }
      void setAcookie(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        acookie_ = value;
        onChanged();
      }
      
      // optional string session_cookie = 3;
      private java.lang.Object sessionCookie_ = "";
      public boolean hasSessionCookie() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSessionCookie() {
        java.lang.Object ref = sessionCookie_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionCookie_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionCookie(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionCookie_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionCookie() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionCookie_ = getDefaultInstance().getSessionCookie();
        onChanged();
        return this;
      }
      void setSessionCookie(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        sessionCookie_ = value;
        onChanged();
      }
      
      // optional string tree_id = 4;
      private java.lang.Object treeId_ = "";
      public boolean hasTreeId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTreeId() {
        java.lang.Object ref = treeId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          treeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTreeId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        treeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTreeId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        treeId_ = getDefaultInstance().getTreeId();
        onChanged();
        return this;
      }
      void setTreeId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        treeId_ = value;
        onChanged();
      }
      
      // optional string node_id = 5;
      private java.lang.Object nodeId_ = "";
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNodeId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        nodeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      void setNodeId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        nodeId_ = value;
        onChanged();
      }
      
      // optional string parent_id = 6;
      private java.lang.Object parentId_ = "";
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParentId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        parentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      void setParentId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        parentId_ = value;
        onChanged();
      }
      
      // optional string parent_list = 7;
      private java.lang.Object parentList_ = "";
      public boolean hasParentList() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getParentList() {
        java.lang.Object ref = parentList_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parentList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParentList(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        parentList_ = value;
        onChanged();
        return this;
      }
      public Builder clearParentList() {
        bitField0_ = (bitField0_ & ~0x00000040);
        parentList_ = getDefaultInstance().getParentList();
        onChanged();
        return this;
      }
      void setParentList(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        parentList_ = value;
        onChanged();
      }
      
      // optional string ip = 8;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ip_ = value;
        onChanged();
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        ip_ = value;
        onChanged();
      }
      
      // optional string user_agent = 9;
      private java.lang.Object userAgent_ = "";
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserAgent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        userAgent_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000100);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      void setUserAgent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        userAgent_ = value;
        onChanged();
      }
      
      // optional string url = 10;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000200);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
      }
      
      // optional string url_info = 11;
      private java.lang.Object urlInfo_ = "";
      public boolean hasUrlInfo() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getUrlInfo() {
        java.lang.Object ref = urlInfo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          urlInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrlInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        urlInfo_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrlInfo() {
        bitField0_ = (bitField0_ & ~0x00000400);
        urlInfo_ = getDefaultInstance().getUrlInfo();
        onChanged();
        return this;
      }
      void setUrlInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        urlInfo_ = value;
        onChanged();
      }
      
      // optional string lzsession = 12;
      private java.lang.Object lzsession_ = "";
      public boolean hasLzsession() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getLzsession() {
        java.lang.Object ref = lzsession_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          lzsession_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLzsession(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        lzsession_ = value;
        onChanged();
        return this;
      }
      public Builder clearLzsession() {
        bitField0_ = (bitField0_ & ~0x00000800);
        lzsession_ = getDefaultInstance().getLzsession();
        onChanged();
        return this;
      }
      void setLzsession(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        lzsession_ = value;
        onChanged();
      }
      
      // optional string user_id = 13;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        userId_ = value;
        onChanged();
      }
      
      // optional string nick = 14;
      private java.lang.Object nick_ = "";
      public boolean hasNick() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNick(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        nick_ = value;
        onChanged();
        return this;
      }
      public Builder clearNick() {
        bitField0_ = (bitField0_ & ~0x00002000);
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      void setNick(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00002000;
        nick_ = value;
        onChanged();
      }
      
      // optional string proxy = 15;
      private java.lang.Object proxy_ = "";
      public boolean hasProxy() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getProxy() {
        java.lang.Object ref = proxy_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          proxy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProxy(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        proxy_ = value;
        onChanged();
        return this;
      }
      public Builder clearProxy() {
        bitField0_ = (bitField0_ & ~0x00004000);
        proxy_ = getDefaultInstance().getProxy();
        onChanged();
        return this;
      }
      void setProxy(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        proxy_ = value;
        onChanged();
      }
      
      // optional string pvtime = 16;
      private java.lang.Object pvtime_ = "";
      public boolean hasPvtime() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public String getPvtime() {
        java.lang.Object ref = pvtime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pvtime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPvtime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        pvtime_ = value;
        onChanged();
        return this;
      }
      public Builder clearPvtime() {
        bitField0_ = (bitField0_ & ~0x00008000);
        pvtime_ = getDefaultInstance().getPvtime();
        onChanged();
        return this;
      }
      void setPvtime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00008000;
        pvtime_ = value;
        onChanged();
      }
      
      // optional string revised_refer = 17;
      private java.lang.Object revisedRefer_ = "";
      public boolean hasRevisedRefer() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public String getRevisedRefer() {
        java.lang.Object ref = revisedRefer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          revisedRefer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRevisedRefer(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        revisedRefer_ = value;
        onChanged();
        return this;
      }
      public Builder clearRevisedRefer() {
        bitField0_ = (bitField0_ & ~0x00010000);
        revisedRefer_ = getDefaultInstance().getRevisedRefer();
        onChanged();
        return this;
      }
      void setRevisedRefer(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00010000;
        revisedRefer_ = value;
        onChanged();
      }
      
      // optional int64 ts = 18;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00020000;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00020000);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string refer = 19;
      private java.lang.Object refer_ = "";
      public boolean hasRefer() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public String getRefer() {
        java.lang.Object ref = refer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          refer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRefer(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        refer_ = value;
        onChanged();
        return this;
      }
      public Builder clearRefer() {
        bitField0_ = (bitField0_ & ~0x00040000);
        refer_ = getDefaultInstance().getRefer();
        onChanged();
        return this;
      }
      void setRefer(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00040000;
        refer_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeValue)
    }
    
    static {
      defaultInstance = new AplusAccessTreeNodeValue(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(main/resources/AplusAccessTreeNode.pro" +
      "to\022!com.etao.data.ep.accesstree.proto\"\340\002" +
      "\n\030AplusAccessTreeNodeValue\022\017\n\007version\030\001 " +
      "\001(\t\022\017\n\007acookie\030\002 \001(\t\022\026\n\016session_cookie\030\003" +
      " \001(\t\022\017\n\007tree_id\030\004 \001(\t\022\017\n\007node_id\030\005 \001(\t\022\021" +
      "\n\tparent_id\030\006 \001(\t\022\023\n\013parent_list\030\007 \001(\t\022\n" +
      "\n\002ip\030\010 \001(\t\022\022\n\nuser_agent\030\t \001(\t\022\013\n\003url\030\n " +
      "\001(\t\022\020\n\010url_info\030\013 \001(\t\022\021\n\tlzsession\030\014 \001(\t" +
      "\022\017\n\007user_id\030\r \001(\t\022\014\n\004nick\030\016 \001(\t\022\r\n\005proxy" +
      "\030\017 \001(\t\022\016\n\006pvtime\030\020 \001(\t\022\025\n\rrevised_refer\030",
      "\021 \001(\t\022\n\n\002ts\030\022 \001(\003\022\r\n\005refer\030\023 \001(\tB=\n!com." +
      "etao.data.ep.accesstree.protoB\030AplusAcce" +
      "ssTreeNodeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_etao_data_ep_accesstree_proto_AplusAccessTreeNodeValue_descriptor,
              new java.lang.String[] { "Version", "Acookie", "SessionCookie", "TreeId", "NodeId", "ParentId", "ParentList", "Ip", "UserAgent", "Url", "UrlInfo", "Lzsession", "UserId", "Nick", "Proxy", "Pvtime", "RevisedRefer", "Ts", "Refer", },
              com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.class,
              com.etao.data.ep.accesstree.proto.AplusAccessTreeNodeProto.AplusAccessTreeNodeValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
